version: "3.3"

services:
  database:
    build:
      context: ./dockerfile/database/
      dockerfile: Dockerfile
    networks: 
      - interview-network
    container_name: interview-db
    ports:
      - 27017:27017

  service:
    build:
      context: . 
      dockerfile: ./dockerfile/service/Dockerfile
    networks: 
      - interview-network
    container_name: interview-service
    restart: on-failure
    depends_on: 
      - database 
    ports:
      - 8888:8888
    volumes:
      - ./config/config.container.json:/config.json
    command:
      - /interview-service

networks:
  interview-network:
    driver: bridge
